# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sampleangularnew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Startup Command
      id: hola
      uses: saurabhrai19/startupcmdaction@v1.8
      with:
        language: angular 
    - name: Echo Startup Command
      run: echo "${{ steps.hola.outputs.startupcmd }}"
    
    - name: installing dependencies
      run: |
        "${{ steps.hola.outputs.startupcmd }}"
        
    - name: npm build, and test
      run: |
        #npm install
        npm run build --if-present
       # npm run test --if-present

    - name: Read tsconfig.json
      id: package
      uses: saurabhrai19/copyfileaction@v1.3
      with:
        path: ./tsconfig.json
    - name: Echo tsconfig.json
      run: echo "${{ steps.package.outputs.content }}"
